name: opentelemetry_otlp
description: OpenTelemetry Protocol (OTLP) files for Dart
version: 0.5.0-dev.1
homepage: https://www.open-telemetry.com
repository: https://github.com/open-telemetry-com/opentelemetry-dart

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  fixnum: ^1.0.1
  protobuf: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  test: ^1.16.0
