name: opentelemetry_api
description: OpenTelemetry API for Dart
version: 0.5.0-dev.2
homepage: https://www.open-telemetry.com
repository: https://github.com/open-telemetry-com/opentelemetry-dart
# publish_to: pub.dev

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  fixnum: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  test: ^1.16.0
