name: opentelemetry_otlp_grpc
description: OpenTelemetry grpc Exporter for the OpenTelemetry Protocol (OTLP)
version: 0.5.0-dev.2
homepage: https://www.open-telemetry.com
repository: https://github.com/open-telemetry-com/opentelemetry-dart
# publish_to: pub.dev

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  fixnum: ^1.0.1
  opentelemetry_api: ^0.5.0-dev.2
  opentelemetry_otlp: ^0.5.0-dev.2
  protobuf: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  opentelemetry_sdk: ^0.5.0-dev.2
  test: ^1.16.0
