name: opentelemetry_otlp_http
description: OpenTelemetry Http Exporter for the OpenTelemetry Protocol (OTLP)
version: 0.5.0-dev.1
homepage: https://www.open-telemetry.com
repository: https://github.com/open-telemetry-com/opentelemetry-dart

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  fixnum: ^1.0.1
  http: ^0.13.5
  #  logging: ^1.0.2
  opentelemetry_api: 0.5.0-dev.1
  opentelemetry_otlp: 0.5.0-dev.1
  opentelemetry_sdk: 0.5.0-dev.1
  protobuf: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  mockito: ^5.3.0
  test: ^1.16.0
